---
title: "Week 2 Day 3 Homework"
output: html_notebook
---

# Question 1
list of lists- wethaer for 3 days with temperature, chance of rain and wind speed
```{r}
weather_forecast <- list(
  thursday = list(temp_deg = 19, chance_of_rain = "10%", wind_speed = 5),
  friday = list(temp_deg = 15, chance_of_rain = "25%", wind_speed = 5),
  saturday = list(temp_deg = 21, chance_of_rain = "5%", wind_speed = 5)
)
```

# Question 2
```{r}
# Chance of rain tomorrow
weather_forecast$thursday$chance_of_rain
# Method 2
weather_forecast[[1]][2]
```
```{r}
# Wind speed the day after tomorrow
weather_forecast$friday$wind_speed
# Method 2
weather_forecast[[2]][3]
```

```{r}
# Wind speed the day after tomorrow
weather_forecast$thursday$temp_deg
# Method 2
weather_forecast[[1]][1]
```

# Question 3

```{r}
two_week_forecast <- matrix(nrow = 14, ncol = 7)

for (num_row in 1:dim(two_week_forecast)[1]){
  for (num_col in 1:dim(two_week_forecast)[2]) {
    two_week_forecast[num_row, num_col]= sample(10:20,1)
  }
}

two_week_forecast
```
# Question 4
```{r}
# Third day of second week
two_week_forecast[2, 3]

# Whole of second week
two_week_forecast[2, ]

# First, third and 5th days of both weeks
two_week_forecast[c(2, 3), c(1, 3, 5)]
```

# Question 5
```{r}
add_pre_text <- function(x){
  if (is.numeric(x)){
      if (x > 10){
        x <- x/2
        }
    paste("The answer is:", x)
  }else{
    if(is.character(x)){
      paste("The answer is:", x)
    }else{
      paste("Invalid Input")
    }
  }
}
```


Test the function
```{r}
add_pre_text(5)
add_pre_text(78)
add_pre_text("char")
add_pre_text(NA)
```

# Question 6
```{r}
compare_vectors <- function(vector_one, vector_two){
  if(all(vector_one == vector_two)){
    check_string <- "Exactly the same" 
  }else{
    if (all(sort(vector_one) == sort(vector_two))){
      check_string <- "The same"
    }else
      check_string <- "Different"
  }
  if (class(vector_one) == class(vector_two)){
    paste(check_string)
  }else{
    paste(check_string, "values but different classes")
  }
}
```

```{r}
a <- c(1, 2, 3)
b <- c("1", 2, 3)

compare_vectors(a, b)
```

# Quesion 7

```{r}
max_value <- 12
times_table <- matrix(nrow = max_value, ncol = max_value)

for (row_count in 1:max_value){
  for(col_count in 1:max_value){
    times_table[row_count, col_count] <- row_count * col_count
  }
}

times_table
```

# Question 8

```{r}
library(tidyverse)
```


```{r}
create_text_histogram <- function(input_vector){
  
  output_table<- input_vector %>%
    table() %>% 
    as.data.frame()
  
  names(output_table)[1] <- "bin_name"
  
  max_char_length <- output_table %>% 
    summarise(max_length = max(str_length(bin_name))) %>% 
    pull()

  
  output_string <- output_table %>% 
    mutate(histogram_string = 
             paste0(strrep(" ", max_char_length - str_length(bin_name)),
                    bin_name, "|", strrep("*", Freq), "\n")) %>% 
    select(histogram_string) %>% 
    pull()
  
  cat("\n", output_string)
    
}
```

```{r}
histogram_values <- c(1, 2, 3, 4, 5, 1, 3, 4, 5, 1, 3, 4, 4, 3, 3, 3, 3)

create_text_histogram(histogram_values)
```

